name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install root deps
        run: npm ci || npm install

      - name: Build frontend
        working-directory: ./
        run: |
          npm run build --workspaces=false || true

      - name: Install server deps
        working-directory: ./server
        run: npm ci || npm install

      - name: Typecheck server
        working-directory: ./server
        run: npx tsc -noEmit

      # Optionally run linters/tests if present
      # - name: Lint
      #   run: npm run lint

